CREATE TABLE IF NOT EXISTS `User_Login` (
  `loginID` int UNSIGNED NOT NULL PRIMARY KEY,
  `username` varchar(50) NOT NULL,
  `password` varchar(50) NOT NULL,
  `nama` varchar(30) NOT NULL,
  `level` varchar(1) NOT NULL,
  `Updated` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  PRIMARY KEY (`loginID`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS Peserta (
    PesertaID int UNSIGNED NOT NULL PRIMARY KEY,
    Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Flag ENUM('Insert','Detele'),
);
CREATE TABLE IF NOT EXISTS Wali (
    WaliID int UNSIGNED NOT NULL PRIMARY KEY,
    Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Flag ENUM('Insert','Detele'),
);
CREATE TABLE IF NOT EXISTS Alamat (
    AlamatID int UNSIGNED NOT NULL PRIMARY KEY,
    PesertaID int,
    Provinsi varchar(150),
    Kabupaten_kota varchar(150),
    Kecamatan varchar(150),
    Kode_Pos varchar(150),
    Alamat varchar(150),
    Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Flag ENUM('Insert','Detele'),
    FOREIGN KEY (PesertaID) REFERENCES Peserta(PesertaID)
);
CREATE TABLE IF NOT EXISTS Panitia (
    PanitiaID int UNSIGNED NOT NULL PRIMARY KEY,
    Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Flag ENUM('Insert','Detele'),
);
CREATE TABLE IF NOT EXISTS Kepala_Sekolah (
    KepalaSekolahID int UNSIGNED NOT NULL PRIMARY KEY,
    Updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Flag ENUM('Insert','Detele'),
);